// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtfnyxmovikhvxqqdedb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0Zm55eG1vdmlraHZ4cXFkZWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDQ5OTYsImV4cCI6MjA3MDgyMDk5Nn0.a_8-yoSLVBRM9lPOvyWzRnJOuxR24ENtcor16gZnB1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});